In [1]:
import numpy as np
#temp | rainfall | humidity
region_d1 = [73 , 20 , 60]
region_d2 = [40 , 20 ,10]
region_d3 = [43 , 10 , 60]

w1 , w2 ,w3 = 0.3 ,0.4 ,0.6

weights =[ w1 ,w2 ,w3]

##function for the calculation
def crop_yield(regiion , weight):
    result = 0 
    for x,w in zip(regiion ,weights):
        result +=x*w
    return result

##call the function
crop_yield(region_d1,w1)
### here we are calculating the dot product , but can do the same thing using numpy , which supoots dot product by default


65.9

In [8]:
import numpy as np
region1_np = np.array(region_d1)
weights_np = np.array(weights)
## dot product calculated
np.dot(region1_np , weights_np)




np.float64(65.9)

In [15]:
## or we can do like this laso 
(region1_np*weights_np).sum()

np.float64(65.9)

In [16]:
climate_data =  np.array([
    [73 , 20 , 60],
    [40 , 20 ,10],
    [43 , 10 , 60]
])

In [18]:
## inspect the length of array using .shape  ----> Row*Column
climate_data.shape

(3, 3)

Note : All elemets in a numpy array should have the same data type 

Note : if a single element in an array is float then all the all the values are converted into the float

now calculate the yield of all region together ---> matrix multiplication


In [19]:
climate_data =  np.array([
    [73 , 20 , 60],
    [40 , 20 ,10],
    [43 , 10 , 60]
])

weights_np

np.matmul(climate_data ,weights_np)


array([65.9, 26. , 52.9])

In [20]:
climate_data @ weights_np #this is sam as matrix multiplication

array([65.9, 26. , 52.9])

workflow ----> import an csv file , convert it into the numpay array , concatenate the data , then save it to folder


In [25]:
import os
##import the csv file
load_data = np.loadtxt("test_data.csv" , delimiter= ',', skiprows=1)
extra_data = np.array([100,90,80]).reshape(-1 ,1)
#concatenate the array
combined_data = np.concatenate((load_data,extra_data),axis=1)

##create a file to save it 
output_folder = "output_data"
os.makedirs(output_folder , exist_ok=True)
np.savetxt(os.path.join(output_folder, "combined_data.csv"), combined_data, delimiter=",", fmt="%.2f")

print("NumPy-only workflow complete!")





NumPy-only workflow complete!


Array Indexing and Slicing

In [28]:
climate_data =  np.array([
    [73 , 20 , 60],
    [40 , 20 ,10],
    [43 , 10 , 60]
])



np.int64(60)

In [29]:
##single element
climate_data[2,2]

np.int64(60)

In [30]:
##subarrays
climate_data[1:]

array([[40, 20, 10],
       [43, 10, 60]])

Creating numpty arrays with some default values


In [32]:
#All Zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
## all ones 

np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
#3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#Random vector --> rand -1to 1

np.random.rand(5)

array([0.72197969, 0.97047283, 0.37676351, 0.86265025, 0.20328203])

In [37]:
## random matrix  --> randn --> -2 to 2

np.random.randn(2,3)

array([[ 0.23846519, -0.6360016 ,  1.01551932],
       [ 0.52231577, -0.45946598, -0.12931399]])

In [38]:
## Fixed values

np.full([2,3] ,10)

array([[10, 10, 10],
       [10, 10, 10]])