In [10]:
import numpy as np

In [11]:
#Print the numpy version and the configuration
np.__version__

'2.1.3'

In [12]:
#. Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# Create a vector with values ranging from 10 to 49
z = np.arange(10,50)
z


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
#Reverse a vector (first element becomes last)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [15]:
#Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
# Find indices of non­zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [17]:
# Create a 3x3 identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Create a 3x3x3 array with random values 
np.random.random((3,3,3))

array([[[0.5922265 , 0.45161014, 0.11561823],
        [0.10503187, 0.31049209, 0.84682588],
        [0.86116893, 0.0086376 , 0.5818878 ]],

       [[0.64357366, 0.45570671, 0.79633196],
        [0.48548699, 0.36254432, 0.63535685],
        [0.67380935, 0.17187378, 0.40001474]],

       [[0.64436372, 0.10754743, 0.85830893],
        [0.36035056, 0.93005552, 0.48565745],
        [0.87154948, 0.75597923, 0.77259468]]])

In [19]:
#Create a 10x10 array with random values and find the minimum and maximum values
z= np.random.random((10,10))
zmin , zmax= z.min() , z.max()
print(z)
print(zmin , zmax)

[[0.96118826 0.70315136 0.14277009 0.90636844 0.89958805 0.00667477
  0.9155129  0.08206389 0.82183719 0.60361242]
 [0.50483673 0.30719976 0.21581412 0.49567057 0.58816807 0.76945265
  0.01990825 0.86395567 0.06925662 0.52040057]
 [0.82014712 0.42279502 0.20870438 0.81193194 0.25177177 0.74240117
  0.79035437 0.762388   0.92997365 0.64993767]
 [0.37912562 0.8259405  0.08978899 0.09005279 0.88538627 0.04303435
  0.07957544 0.82125519 0.99755974 0.47575081]
 [0.73887243 0.93318295 0.05571281 0.44575006 0.13524942 0.16323435
  0.49092799 0.02075313 0.49766453 0.35817232]
 [0.15175516 0.64885757 0.94381414 0.12539654 0.89798473 0.23503596
  0.90348793 0.56634374 0.17423237 0.4125702 ]
 [0.45094399 0.14569422 0.82227538 0.64347032 0.94779114 0.87319393
  0.68417723 0.11433293 0.09510625 0.06289426]
 [0.77149325 0.44900792 0.49359804 0.69290073 0.24421355 0.85697592
  0.34694102 0.72924102 0.18007143 0.99648588]
 [0.60966077 0.09066177 0.42127434 0.0271282  0.36252564 0.83758577
  0.97878516

In [20]:
#Create a random vector of size 30 and find the mean value
z= np.random.random((30))
z.mean()


np.float64(0.5021037399670134)

In [21]:
#Create a 2d array with 1 on the border and 0 inside
np.random.random((10 ,10))

array([[0.21771763, 0.58113449, 0.36544554, 0.16605033, 0.88012857,
        0.36243037, 0.8302476 , 0.41591101, 0.87776171, 0.37668804],
       [0.84226606, 0.96100723, 0.9919278 , 0.9959246 , 0.65274691,
        0.32946254, 0.96705101, 0.18052845, 0.95307349, 0.39757952],
       [0.57554797, 0.25681166, 0.70990304, 0.59130688, 0.00501175,
        0.24647958, 0.0602787 , 0.07518779, 0.83636492, 0.17842093],
       [0.10967696, 0.47795477, 0.8964329 , 0.88387385, 0.67308188,
        0.7453706 , 0.6174847 , 0.49985139, 0.41805293, 0.89127079],
       [0.9705634 , 0.60815211, 0.53085203, 0.79193481, 0.896271  ,
        0.23628789, 0.68386962, 0.00773012, 0.49912983, 0.14730955],
       [0.02508611, 0.22494757, 0.07168344, 0.63106328, 0.76522706,
        0.32140034, 0.50124809, 0.97428959, 0.80785779, 0.90141816],
       [0.96095206, 0.97179528, 0.55225448, 0.13348093, 0.97605437,
        0.86553169, 0.72097192, 0.73970031, 0.83445445, 0.77245138],
       [0.88296088, 0.54977884, 0.6303638

In [22]:
#What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

In [23]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
data = np.array([1,2,3,4])
print(data)

[1 2 3 4]


In [24]:
# matrix = np.diag(data)
matrix = np.diag(data , k=-1)
matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [26]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
# np.random.rand(6, 7, 8)
print(np.unravel_index(100,(6,7,8))) ## 100 is the position of the element and  a (6,7,8) shape array


(np.int64(1), np.int64(5), np.int64(4))


Normalization is the process of transforming data to a standard scale, usually in the range [0, 1].

- Why Normalize Data?
In many cases, your data might have values with different scales. For example:

Age: 0–100

Income: 10,000–1,000,000

If you don’t normalize:

Algorithms like KNN, logistic regression, SVM, or gradient descent-based models might give more importance to features with larger values (e.g., income over age).

Xnormalized = (x-xmin ) / (xmax - xmin)


 
​
 


In [40]:
#Normalize a 5x5 random matrix 
z = np.random.randint(1, 100, (5, 5))
zmax , zmin = z.max() ,z.min()
normalized = (z-zmin)/(zmax-zmin)
print(z)
print("-----------------------")
print(normalized)

[[49 60 56  4 24]
 [88 12 53 30 44]
 [91 58 26 93 59]
 [ 2 72 98 19 93]
 [24 75 57 47 36]]
-----------------------
[[0.48958333 0.60416667 0.5625     0.02083333 0.22916667]
 [0.89583333 0.10416667 0.53125    0.29166667 0.4375    ]
 [0.92708333 0.58333333 0.25       0.94791667 0.59375   ]
 [0.         0.72916667 1.         0.17708333 0.94791667]
 [0.22916667 0.76041667 0.57291667 0.46875    0.35416667]]


In [43]:
#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
m1 = np.ones((5,3))
m2 = np.ones((3,2))

dot_product = np.dot(m1 , m2)
dot_product

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [46]:
#Given a 1D array, negate all elements which are between 3 and 8, in place.
z = np.arange(11)
z[(z>=3) & (z<=8)] *= -1
z



array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [49]:
print(sum(range(5) , -1))

9


In [53]:
#Consider two random array A anb B, check if they are equa

A = np.random.randint(0,2,5)   ##np.random.randint(low, high, size)
B = np.random.randint(0,2,5) 
equal = np.allclose(A,B)
print(equal)

False


In [66]:
#Create random vector of size 10 and replace the maximum value by 0

z= np.random.random(10)
max_index = z.argmax()
print(max_index)
z[max_index] = 0
print(z)



2
[0.1748089  0.72302448 0.         0.83923213 0.36499563 0.63009746
 0.53513317 0.27146772 0.78254138 0.94910757]


In [72]:
#How to find the closest value (to a given scalar) in an array? 

z= np.random.random(10)
target = 0.777
diff = np.abs(z-target)
diff
min_index = diff.argmin()
print(z)
print("-----")
print(z[min_index])

[0.53062795 0.03042055 0.61710234 0.25388952 0.25890975 0.70721736
 0.39109491 0.78538663 0.08148524 0.82318378]
-----
0.7853866291954678


In [73]:
#What is the equivalent of enumerate for numpy arrays?
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [78]:
# Compute a matrix rank

#The rank of a matrix is the maximum number of linearly independent rows or columns.
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
rank = np.linalg.matrix_rank(A)
print(rank)



2


In [82]:
# How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(Z)
print("----")
print(np.bincount(Z).argmax())

[4 8 9 5 0 1 1 8 1 8 8 5 3 0 6 6 1 9 6 8 7 0 7 5 1 8 7 0 5 0 2 0 0 4 6 4 7
 6 7 6 5 4 2 2 9 8 9 7 8 9]
----
8
